### ISSUE TITLE
Suggestion: repo cleanup

### ISSUE THREAD

**Issue by matteobachetti** [xragua/xraybinaryorbit#1]
In general, directories like `__pycache__`, `build` or `*egg-info*` should not be part of the shared code, as well as `.DS_STORE` files and such

**Comment by xragua** [comment]
Ok, I'll remove them, thanks!

**Comment by warrickball** [comment]
If you've made these changes (which at a glance I think you have), you may want to close this issue.

If possible, don't forget to tag the JOSS review with openjournals/joss-reviews#7220 so that this activity is linked there and easier to find.

But thanks! This is a perfectly reasonable way to proceed with the review.

**Comment by xragua** [comment]
@openjournals/joss-reviews/issues/7220, @matteobachetti ,@warrickball
 I close this issue as is already solved.
Thank you!

**Comment by matteobachetti** [comment]
As of now, there is still another __pycache__ directory left, plus the `dist` directory which is also not usually shared
